# ...

[package]
name = "ycriatimt"
version = "0.1.0"
edition = "2021"
default-run = "ycriatimt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"

[profile.release]
cargo-flags = ["--release"]
